# Generated by Django 4.1.3 on 2022-11-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter fullname', max_length=100, verbose_name='Fullname')),
                ('telegram_id', models.CharField(help_text='Enter Chat Id', max_length=20, unique=True, verbose_name='User ID')),
                ('language', models.CharField(default='uz', help_text='Enter Language', max_length=10, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Bot User ',
                'verbose_name_plural': 'Bot Users ',
                'db_table': 'Bot Foydalanuvchilari',
            },
        ),
    ]
